FROM node:22

VOLUME /db

WORKDIR /app

ADD dist/api api/

RUN npm install sqlite3

EXPOSE 3000

ENV HOST=0.0.0.0 PORT=3000 SQLITE3_PATH=/db/db.sqlite NODE_ENV=production

CMD ["node", "api/index.mjs"]
