name: Upload Release Artifact

on:
  release:
    types:
      - published

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: 'npm'

      - name: Cache Node dependencies
        uses: actions/cache@v4
        id: npm-cache
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install dependencies
        run: npm ci

      - name: Build application
        env:
          NODE_OPTIONS: --openssl-legacy-provider
        run: |
          npm run build
          mkdir -p tmp
          mv dist tmp

      - name: Upload build
        uses: actions/upload-artifact@v4
        with:
          name: dist_folder
          path: tmp
          retention-days: 1

  artifacts:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v4

      - name: Download build
        uses: actions/download-artifact@v4
        with:
          name: dist_folder

      - name: Prepare Release Artifact
        run: |
          jq .version lerna.json > dist/version.txt
          cp -r server/migrations dist
          cd dist/
          zip -r ../app.zip .
          cd ..

      - name: Upload Release Artifact
        uses: softprops/action-gh-release@v2
        with:
          files: |
            app.zip
            docker-compose.yml
            nginx.conf
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

  docker:
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        include:
          - file: client/Dockerfile
            image: villekulla/booking-app
          - file: server/Dockerfile.api
            image: villekulla/booking-api
          - file: server/Dockerfile.migrations
            image: villekulla/booking-migrations

    steps:
      - uses: actions/checkout@v4

      - name: Download build
        uses: actions/download-artifact@v4
        with:
          name: dist_folder

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: villekulla
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ matrix.image }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ${{ matrix.file }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
