name: Upload Release Artifact

on:
  release:
    types:
      - published

jobs:
  artifacts:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Download build
        uses: actions/download-artifact@v4
        with:
          name: dist_folder

      - name: Prepare Release Artifact
        run: |
          jq .version lerna.json > dist/version.txt
          cp -r server/migrations dist
          cd dist/
          zip -r ../app.zip .
          cd ..

      - name: Upload Release Artifact
        uses: softprops/action-gh-release@v2
        with:
          files: |
            app.zip
            docker-compose.yml
            nginx.conf
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - file: client/Dockerfile
            image: villekulla/booking-app
          - file: server/Dockerfile.api
            image: villekulla/booking-api
          - file: server/Dockerfile.migrations
            image: villekulla/booking-migrations

    steps:
      - uses: actions/checkout@v4

      - name: Download build
        uses: actions/download-artifact@v4
        with:
          name: dist_folder

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: villekulla
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ matrix.image }}

      - name: Create short SHA
        id: short-sha
        run: |
          id=$(echo ${{github.sha}} | cut -c 1-5)
          echo "short-sha=$id" >> "$GITHUB_OUTPUT"

      - name: Debug image tag
        run: echo "Tag -> ${{ matrix.image }}:${{ steps.short-sha.outputs.short-sha }}"

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ${{ matrix.file }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
